# cloudbuild.yaml 
steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ["install"]
  dir: 'my-app'
- name: 'gcr.io/cloud-builders/npm'
  args: ["run", "build"]
  dir: 'my-app'
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]
  dir: 'my-app'
timeout: 1600s