
runtime: nodejs10
service: default
handlers: 


- url: /(.*\..+)$
  static_files: build/\1
  upload: build/(.*\..+)$
  http_headers:
    Access-Control-Allow-Origin: https://front-end-dot-servertest-285416.nw.r.appspot.com/

- url: /.*
  static_files: build/index.html
  upload: build/index.html
  http_headers:
    Access-Control-Allow-Origin: https://servertest-285416.nw.r.appspot.com